version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: docker:latest
    working_directory: ~/base
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker info
          docker build --pull --rm=false -t treblefm/base .

          docker build --pull --rm=false -t test tests/nvm
          docker run --rm -it test

          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push treblefm/base
