version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/base
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker info
          docker build --pull --rm=false -t treblefm/base .

  deploy:
    docker:
      - image: docker:latest
    working_directory: ~/base
    steps:
      - run: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          docker push treblefm/base

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
